### ISSUE TITLE
add very simple wrapper functions for rmapshaper functions

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSpatialUtils#16]
The **rmapshaper** package has useful functions to "dissolve" and perhaps other useful things. (We already have one for "simplify".)

We should wrap these functions in super-simple functions of our own that take as few arguments as possible (followed by ...) and make it very easy to do the most common things without having to learn **rmapshaper**.

**Comment by helenmiller16** [comment]
You say we already have a wrapper function for "simplify" -- where is it?

**Comment by helenmiller16** [comment]
Never mind. I found it.
