### ISSUE TITLE
loadSpatialData() enhancements

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSpatialUtils#24]
The `loadSpatialData()` function currently ignores directories and expects everything else to be a `.RData` file.

1. We should enhance the function signature with `extensions = c("rda", "RData")` and ignore any files that don't match.

2. We may also need a `priorityExtension = "rda"` parameter so we can decide which extension to use in case there is more than one data file. The `# ----- validateParameters -----` section should check that `priorityExtnesion %in% extensions`.

**Comment by lagerratrobe** [comment]
Item 1 is more easily accomplished by writing the appropriate regex in the "pattern" for `list.files()`.
```
randre@Cetautomatix  ~/Data/Spatial
$ ls -1
EEZCountries.RData
EPARegions.RData
HIFLDFederalLands.RData
MTBSBurnArea.RData
NaturalEarthAdm1.RData
OSMTimezones.RData
TMWorldBorders.RData
USCensusCounties.RData
USCensusStates.RData
USCensusUrbanAreas.RData
USFSRangerDistricts.RData
WorldTimezones.RData
foo.rda <- dummy file
xyz.r <- dummy file
zxy.R <- dummy file
```
Only match `.Rdata` and `.rda`

```
> foo <- list.files(pattern = "*\\.[rR][dD]a?t?a")
> for (match in foo) { message(match)}
EEZCountries.RData
EPARegions.RData
foo.rda
HIFLDFederalLands.RData
MTBSBurnArea.RData
NaturalEarthAdm1.RData
OSMTimezones.RData
TMWorldBorders.RData
USCensusCounties.RData
USCensusStates.RData
USCensusUrbanAreas.RData
USFSRangerDistricts.RData
WorldTimezones.RData
```

Item 2 appears to be optional.  Let me know if this is something that you still want.

**Comment by jonathancallahan** [comment]
I don't think using a pattern is a good idea because it assumes we know what people will name their R binary files or that end users know how to use regular expressions. I don't think either of those is a safe bet.

Accepting a vector of extensions seems to me to be the more understandable and end-user-flexible solution and I would prefer going back to that.
