### ISSUE TITLE
create convertFederalLands() function

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSpatialUtils#25]
A federal lands dataset is highly relevant for our work with environmental monitoring. This is only one of the many datasets available at Homeland Infrastructure Foundation-Level Data (HIFLD): 

https://hifld-geoplatform.opendata.arcgis.com 

Clicking on the "Boundaries" category led me to "National Forests" which has several interesting datasets, one of which is:

https://hifld-geoplatform.opendata.arcgis.com/datasets/federal-lands

Clicking on "Downloads" and copying the link for "shapefile" I was able to get the data URL:

https://opendata.arcgis.com/datasets/2bb32a6e72414e28aaf72f9dc99d3412_0.zip

Using this data source, the tasks are:

- [x]  Create `R/convertFederalLands.R` based on `R/CONVERT_TEMPLATE.R`.
- [ ] Create `vignettes/articles/federalLands.Rmd` which highlights what can be done with this dataset.

**Comment by lagerratrobe** [comment]
Need to verify that the harmonization features are all present.  In conversation with Jonathan, I think we discovered that the ID column is missing.  Will verify that the rest is in place as well.

**Comment by lagerratrobe** [comment]
This should be good to go now.
