### ISSUE TITLE
installedSpatialData()

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSpatialUtils#30]
We should have a function that shows what data is currently installed locally and also describes what it is. This function can be developed in steps:

*Step 1* -- Generate a list of names in the locally assigned SpatialDataDir. The following snippet describes how this might be done:

```
list.files(getSpatialDataDir()) %>% 
  stringr::str_extract(".*[^\\.RData]") %>%  # extract all characters up to ".RData"
  stringr::str_replace("_0\\d$","") %>%      # remove _0# (could use this technique above)
  sort() %>% 
  unique()
```

This result is useful but not that informative

*Step 2* -- Given that convert~ scripts are added infrequently, we can add a `harmonizedDatsets` list as a data object inside `MazamaSpatialUtils.R` with a *brief* description attached to each dataset name.

*Step 3* -- The `installedSpatialData()` function should invisibly return the vector of all installed dataset names (_e.g._ `"USCensusCounties"`) including simplified versions by default. But, if `verbose = TRUE` (default), it can spit out a human readable, nicely formatted bunch of text using the descriptions in `harmonizedDatasets`.

Here is a working example of what the output could look like. Note that you have indent text strings and use line continuation at character 80 to get the nicely indented output.

```
# Vector of available datasets
datasetNames <- c("USCensusCBSA", "USFSRangerDistricts")

# List of lists with text info about datasets
datasetInfoList <- list(
  USCensusCBSA = list(
    summary = "U.S. Census Core Based Statistical Areas", 
    details = "\
  The USCensusUrbanAreas layer is a SpatialPolygonsDataFrame which represent the \
  urban areas delineated by the US Census that represent densely developed \
  territory."
  ),
  USFSRangerDistricts = list(
    summary = "U.S. Forest Service Ranger districts ", 
    details = "\
  The USFSRangerDistricts layer is a SpatialPolygonsDataFrame representing U.S. \
  Forest Service ranger district administrative boundaries. Ranger districts are \
  sub units of National Forests intended to identify the specific organizational \
  units that administer areas."
  )
)

# To avoid concatenating inside a loop (dangerously slow), create a list of
# text strings to be pasted together at the end.
datasetTextList <- list() 
for ( datasetName in datasetNames ) {
  
  datasetTextList[[datasetName]] <-
    sprintf(
      "%s -- %s\n\t%s",
      datasetName,
      datasetInfoList[[datasetName]]$summary,
      datasetInfoList[[datasetName]]$details
    )
  
}
```

**Comment by lagerratrobe** [comment]
__Default behavior:__ invisibly return the vector of all installed dataset names (e.g. "USCensusCounties") including simplified versions by default.

__Optional Behavior:__ `verbose = TRUE` spit out a human readable, nicely formatted bunch of text using the descriptions in harmonizedDatasets.

At its heart, this is simply a utility that returns the names of .RData files located in the _SpatialDataDir_  with an optinal parameter to provide a succinct description of each dataset represented by the filename.

I have implemented a version of this in local_roger for review.
