### ISSUE TITLE
ensure existence of required parameter "polygonID" 

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSpatialUtils#33]
All datasets need to adhere to the "package internal standards" defined in `vignettes/MazamaSpatialUtils.Rmd`:

```
The 'package internal standards' are very simple.

1) Every spatial dataset **must** contain the following columns:

* polygonID -- unique identifier for each polygon
* countryCode -- country at centroid of polygon (ISO 3166-1 alpha-2)

...
```

This column is required so that it can always be found by functions like `summarizeByPolygon()`.

The easiest and most harmonized way to ensure the existence of this field this is to always call `convertPolygons()` which will do one of two things:
1. if polygons are properly organized, just add `polygonID`
2. if needed, reorganized polygons first and then add `polygonID`

The following convert scripts need to be updated to call `convertPolygons()`:

- [ ] `convertHIFLDFederalLands.R` -- No unique identifier currently set.
- [ ] `convertMTBSBurnArea.R` -- Looks like `FIre_ID` is the unique identifier that should be passed to `organizePolygons()`.
- [ ] `convertUSCensusUrbanAreas()`  -- Looks like `GEOID10` is the unique identifier that should be passed to `organizePolygons()`.

A final task:
- [ ] Update `README.md` to match the language in `MazamaSpatialUtils.Rmd` describing the "package internal standards"

**Comment by lagerratrobe** [comment]
Pretty sure I had added polygonID to HIFLDFederalLands, but let me check.

```
> head(HIFLDFederalLands@data$polygonID)
[1] "38915" "39370" "39391" "39410" "39431" "39443"
``

Ah, it's a character string.  But you know what?  I'll modify all 3 of these to just use organizePolygons()

**Comment by lagerratrobe** [comment]
Updated the 3 convert scripts to all use `organizePolygons()` with a unique ID.  For consistency, I did not choose to use the fields specified above for the Burn and Urban areas and used a sequential ID instead.  This simplifies working with the data sets when they are viewed in an attribute-only setting.

**Comment by lagerratrobe** [comment]
`README.md` says:

```
The ‘package internal standards’ are very simple. Every spatial dataset will
have at least one of the following, consistently named columns of data:

 * `polygonID` – unique identifier associated with each polygon
 * `countryCode` – ISO 3166-1 alpha-2
 * `stateCode` – ISO 3166-2 alpha-2
 * `timezone` – Olson timezone

If another column contains this data, that column must be renamed or
duplicated with the internally standardized name. This simple level of
consistency makes it possible to generate maps for any data that is ISO encoded.
It also makes it possible to create functions that return the country, state or
timezone associated with a set of locations.
```

`MazamaSpatialUtils.Rmd` states:

```
1) Every spatial dataset **must** contain the following columns:

* polygonID -- unique identifier for each polygon
* countryCode -- country at centroid of polygon (ISO 3166-1 alpha-2)

2) Spatial datasets with timezone data **must** contain the following column:

* timezone -- Olson timezone

3) Spatial datasets at scales smaller than the nation-state **should** contain the following column:

* stateCode -- 'state' at centroid of polygon (ISO 3166-2 alpha-2)

If other columns contain these data, those columns must be renamed or duplicated with the 
internally standardized name. This simple level of consistency makes it possible to generate 
maps for any data that is ISO encoded. It also makes it possible to create functions that 
return the country, state or timezone associated with a set of locations.
```
Updated `README.md` as requested.
