### ISSUE TITLE
Consider updating WorldEEZ data

### ISSUE THREAD

**Issue by lagerratrobe** [MazamaScience/MazamaSpatialUtils#38]
Currently at version 8.  Version 11 now available.

Changelogs from later versions below.
http://www.marineregions.org/files/eez_v9_changes.php
http://www.marineregions.org/files/eez_v10_changes.php
http://www.marineregions.org/files/eez_v11_changes.php

**Comment by tinaisat** [comment]
Citation: 
Flanders Marine Institute (2019). Maritime Boundaries Geodatabase: Maritime Boundaries and Exclusive Economic Zones (200NM), version 11. Available online at http://www.marineregions.org/. https://doi.org/10.14284/386
