### ISSUE TITLE
convertWeatherZones points to old assets

### ISSUE THREAD

**Issue by JimColl** [MazamaScience/MazamaSpatialUtils#43]
**Issue**: Some of the the weather service related convert calls seem to point to old versions of assets.  reprex?:
``` R
> library(MazamaSpatialUtils)
> packageVersion("MazamaSpatialUtils")
[1] ‘0.6.4’
> setSpatialDataDir(paste0(basedir, "/data/misc"))
> convertWeatherZones(nameOnly = FALSE, simplify = FALSE)
trying URL 'https://www.weather.gov/source/gis/Shapefiles/WSOM/z_02oc18.zip'
Error in utils::download.file(url, filePath) : 
  cannot open URL 'https://www.weather.gov/source/gis/Shapefiles/WSOM/z_02oc18.zip'
In addition: Warning message:
In utils::download.file(url, filePath) :
  cannot open URL 'https://www.weather.gov/source/gis/Shapefiles/WSOM/z_02oc18.zip': HTTP status was '404 Not Found'
```
A quick peak at https://www.weather.gov/gis/PublicZones shows it's old.  I'd attempt to help fix it but I'm sure I'd just make it worse.

**Comment by jonathancallahan** [comment]
New weather zones at: https://www.weather.gov/source/gis/Shapefiles/WSOM/z_08se21.zip

All AWIPS basemap shape files available here: https://www.weather.gov/gis/AWIPSShapefiles

**Comment by JimColl** [comment]
Let me throw a current but will undoubtedly be an outdated link on this and close it to tidy up.  Thanks!
https://www.weather.gov/source/gis/Shapefiles/WSOM/z_08mr23.zip from https://www.weather.gov/gis/PublicZones
