### ISSUE TITLE
updated county FIPS codes

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSpatialUtils#44]
Just heard this from Itea at the USFS. We should see if a more recent updated of the USCensusCounties dataset makes these corrections.

----- >8 -----

The model data includes three area_identifiers (county FIPS codes including state prefixes) that don't match anything already in our database.
* 02270
* 51515
* 46113

`02270` used to be Wade Hampton Census Area in Alaska.  In 2015 it was renamed to Kusilvak Census Area and given the FIPS code `02158`

Not-so-fun-fact:  worst unemployment and fifth poorest county-equivalent in country (by recent data).

`51515` used to be the independent Virginia city of Bedford.  In 2013 it was absorbed into Bedford County `51019`

`46113` used to be  Shannon County in South Dakota, which was renamed to Oglala Lakota county in 2015 and given the FIPS code `46102` (you'll note the unusual even number).

Ideally we can change these in the input, but if it's a lot of work (or even just something we don't have time to do right now) I can fix manually, or we can ignore for the moment.

**Comment by tinaisat** [comment]
They are updated now and reflected in USCensusCounties
