### ISSUE TITLE
Error in exists(dataset) : first argument has length > 1

### ISSUE THREAD

**Issue by natalie-robinson** [MazamaScience/MazamaSpatialUtils#74]
When I use loadSpatialData() for counties I get a group of four spatial polygon dataframes in my environment ('USCensusCounties', 'USCensusCounties_01', 'USCensusCounties_02', 'USCensusCounties_05').  This is now causing getUsCounty() to fail, with error: Error in exists(dataset) : first argument has length > 1.

This same issue arises with getState().

I can overcome the problem by looping over all county (or state) datasets, getting the county (or state), then keeping the unique value from the loop - but then another issue arises (see git issue "warning in showSRID").

This behavior is new with MazamaSpatialUtils version: MazamaSpatialUtils_0.7.6

Here's some info on my system:
R version 4.1.1 (2021-08-10)
MazamaSpatialUtils_0.7.6
sp_1.4-5
MazamaCoreUtils_0.4.10

**Comment by jonathancallahan** [comment]
Natalie,

We are trying to send all issues like this to a Slack Workspace dedicated to "Mazama Package Support". This helps is collect answers in a single place where others can find them and helps build a small "community of practice" among users of our R packages.

I've sent you an invitation.

**Comment by natalie-robinson** [comment]
Thank you @jonathancallahan.  I have added the bug reports to the slack channel. Cheers,
