### ISSUE TITLE
move code from localExamples/

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSpatialUtils#8]
The TimezoneTest.R script in here should be part of a "Simplified Shapes" vignette that describes the functionality, its memory limits and shows a couple of plots along with the timing results in TimezoneTest.R

Note that very large vignettes are not allowed by CRAN so we have to avoid them -- e.g. the esriMap vignette. We want to keep this as an "article" in the pkgdown website but not include it in the R package.

Reading on one Hadley Wickham site (perhaps docs for pkgdown?) I saw a suggestion that you can have pkgdown articles that are not part of the R package by putting them in a subdirectory of vignettes/. (And then add that directory to .Rbuildignore?)

**Comment by tbergama** [comment]
@jonathancallahan 
Should the "Simplified Shapes" vignette describe the functionality and memory limits of
1. TimezoneTest.R script
1. getTimezone() function
1. the use of rmapshaper::ms_simplify() in conjunction with getTimezone()?
or something else?
